### PR TITLE
Simplify Grid Excercise

### PR DESCRIPTION
**Pull request by p0wl**
[Yesterday](https://www.meetup.com/opentechschool-hamburg/events/256719890/) the grid challenge was by far the one I saw the most people struggle. Renaming the counter variables to `column` & `row` helped a lot, so I renamed it in the material and gave a hint that the `row` variable is needed.

### CODE REVIEW

**Comment by escapedcat** [comment]
Yes please. This would help a lot. People didn't understand that `count` is a variable.

**Comment by p0wl** [comment]
hmm, any objections @xMartin? who else is maintaining this repository? @fallera can you merge this?

**Comment by xMartin** [comment]
Thanks a lot for your effort! I do know this exercise is the hardest part and we struggle to make it easier for the learners.

I really like the additional " (one for columns, one for rows)"!

As for the new naming, I think we should keep `count` as a starting point as it makes sense for the previous one-dimensional exercises and I'm not sure "column" would be confusing here. How about adding it as a suggestion to the description to introduce a "column" and a "row" variable? Or "columnCount"?

**Comment by p0wl** [comment]
I think `column` also makes sense in the one-dimensional exercise. Also, if the code starts with `count` I guess the people would not rename it to `column` in the grid exercise, but rather think `column` and `row` have to be added both.

for me `columnCount` sounds like "number of columns in total", but since it is the current column, I would go with just `column`.

I would like to try `column` and  `row` and hear feedback from the next session with this material. If it is still very confusing, we should improve the exercise further or maybe think of a different one with less frustration potential (maybe one where infinite loops don't happen as easy).

**Comment by escapedcat** [comment]
> maybe one where infinite loops don't happen as easy  

Agreed, we kinda went by: "Oh, I just noticed your fan is going wild. Can I help?"

**Comment by p0wl** [comment]
any updates on this?

**Comment by xMartin** [comment]
Sorry for the silence. Let's try it. I'm not convinced but let's see what feedback we get.

Thank you so much for your interest and effort!

**Pull request merged**
